### PR TITLE
Create contact page in mobile app

### PR DESCRIPTION
**Pull request by jocontreras**
**PT Story:** https://www.pivotaltracker.com/story/show/144022365

**Changes proposed in this PR:**
Add contact tab
Add contact view
Add ionic card

**What I have learned working on this feature:**
Add style to ionic card 

**Screenshot:**

screen shot 2017-04-21 at 11 16 24 am

### CODE REVIEW

**Review by diraulo — APPROVED** [review]
Looks okay for me. But could be interesting to allow the Admin/Owner to set these contact details from the Backend, makes it easy for them to update them as time goes. But that could be the object of a separate feature.

**Comment by jocontreras** [comment]
Thanks Raoul we will add that feature.

**Review by tochman — APPROVED** [review]
I agree with @diraulo Add a ticker for updating that info on the back-end.

**Comment by jocontreras** [comment]
Thanks Thomas, we will add it in our PT.

**Pull request merged**
